const postObj = {
  post_id: 1,
  writer_user_id: 1,
  writer_name: 'hyoeun.kim',
  writer_user_photo_url: '@/assets/img/vue_logo.png',
  title: '프론트엔드 스터디 회고 1 : Vuex와 Pinia',
  content:
    '<p>안녕하세요, 반갑습니다.</p><p><strong>맛있는 점심 어떠세요</strong></p><p><i><strong>치킨</strong></i></p><p><a href="https://www.naver.com">https://www.naver.com</a></p><p>에서 먹을 수 있어요.</p><h2>혹은 피자도 괜찮고</h2><h3>족발도 나쁘지 않아요</h3><blockquote><p>이런 거도 괜찮네</p></blockquote><p>안녕하세요, 반갑습니다.</p><p><strong>맛있는 점심 어떠세요</strong></p><p><i><strong>치킨</strong></i></p><p><a href="https://www.naver.com">https://www.naver.com</a></p><p>에서 먹을 수 있어요.</p><h2>혹은 피자도 괜찮고</h2><h3>족발도 나쁘지 않아요</h3><blockquote><p>이런 거도 괜찮네</p></blockquote><p>안녕하세요, 반갑습니다.</p><p><strong>맛있는 점심 어떠세요</strong></p><p><i><strong>치킨</strong></i></p><p><a href="https://www.naver.com">https://www.naver.com</a></p><p>에서 먹을 수 있어요.</p><h2>혹은 피자도 괜찮고</h2><h3>족발도 나쁘지 않아요</h3><blockquote><p>이런 거도 괜찮네</p></blockquote><p>안녕하세요, 반갑습니다.</p><p><strong>맛있는 점심 어떠세요</strong></p><p><i><strong>치킨</strong></i></p><p><a href="https://www.naver.com">https://www.naver.com</a></p><p>에서 먹을 수 있어요.</p><h2>혹은 피자도 괜찮고</h2><h3>족발도 나쁘지 않아요</h3><blockquote><p>이런 거도 괜찮네</p></blockquote><p>안녕하세요, 반갑습니다.</p><p><strong>맛있는 점심 어떠세요</strong></p><p><i><strong>치킨</strong></i></p><p><a href="https://www.naver.com">https://www.naver.com</a></p><p>에서 먹을 수 있어요.</p><h2>혹은 피자도 괜찮고</h2><h3>족발도 나쁘지 않아요</h3><blockquote><p>이런 거도 괜찮네</p></blockquote>',
  tag_list: ['frontend', 'vue', 'vuex'],
  thumbnail_url: '@/assets/img/vue_logo.png',
  created_at: '2022.06.16',
  updated_at: '2022.06.16',
  published_at: '2022.06.16',
  approver_user_id: 3,
  status: 'W',
  view_count: 34,
  like_count: 35,
  is_like: false,
  reject_content: '정보에 오류가 있는 것 같으니 확인 바랍니다.',
  claim_content:
    '최신 내용으로 작성하여 기존 내용과 차이가 있는 부분이 있습니다. 정보의 오류는 아니니 다시 고려해주시면 감사하겠습니다.',
}

const postsArr = [
  {
    post_id: 1,
    writer_user_id: 'hyoeun.kim@flitto.com',
    writer_name: '김효은',
    title: '프론트엔드 스터디 회고',
    content:
      '안녕하세요. 플리토입니다! 이번 플리토 Server팀 안녕하세요. 플리토입니다! 이번 플리토 Server팀 안녕하세요. 플리토입니다! 이번 플리토 Server팀 안녕하세요. 플리토입니다! 이번 플리토 Server팀 안녕하세요. 플리토입니다! 이번 플리토 Server팀 안녕하세요. 플리토입니다! 이번 플리토 Server팀 안녕하세요. 플리토입니다! 이번 플리토 Server팀',
    created_at: '2022-08-01',
    updated_at: '2022-08-01',
    published_at: '2022-08-01',
    approver_user_id: 'hyoeun.kim@flitto.com',
    status: 'P',
    view_count: 300,
    like_count: 100,
    thumbnail_url: '',
    writer_user_photo_url: '',
    tag_list: ['Frontend', 'Vue.js'],
  },
  {
    post_id: 2,
    writer_user_id: 'hyoeun.kim@flitto.com',
    writer_name: '김효은',
    title: '프론트엔드 스터디 회고',
    content: '안녕하세요. 플리토입니다! 이번 플리토 Server팀',
    created_at: '2022-08-01',
    updated_at: '2022-08-01',
    published_at: '2022-08-01',
    approver_user_id: 'hyoeun.kim@flitto.com',
    status: 'P',
    view_count: 300,
    like_count: 100,
    thumbnail_url: '',
    writer_user_photo_url: '',
    tag_list: ['Frontend', 'Vue.js', 'React.js'],
  },
  {
    post_id: 3,
    writer_user_id: 'hyoeun.kim@flitto.com',
    writer_name: '김효은',
    title: '프론트엔드 스터디 회고',
    content: '안녕하세요. 플리토입니다! 이번 플리토 Server팀',
    created_at: '2022-08-01',
    updated_at: '2022-08-01',
    published_at: '2022-08-01',
    approver_user_id: 'hyoeun.kim@flitto.com',
    status: 'P',
    view_count: 300,
    like_count: 100,
    thumbnail_url: '',
    writer_user_photo_url: '',
    tag_list: ['Java'],
  },
  {
    post_id: 4,
    writer_user_id: 'hyoeun.kim@flitto.com',
    writer_name: '김효은',
    title: '프론트엔드 스터디 회고',
    content: '안녕하세요. 플리토입니다! 이번 플리토 Server팀',
    created_at: '2022-08-01',
    updated_at: '2022-08-01',
    published_at: '2022-08-01',
    approver_user_id: 'hyoeun.kim@flitto.com',
    status: 'P',
    view_count: 300,
    like_count: 100,
    thumbnail_url: '',
    writer_user_photo_url: '',
    tag_list: ['Next.js'],
  },
  {
    post_id: 5,
    writer_user_id: 'hyoeun.kim@flitto.com',
    writer_name: '김효은',
    title: '프론트엔드 스터디 회고',
    content: '안녕하세요. 플리토입니다! 이번 플리토 Server팀',
    created_at: '2022-08-01',
    updated_at: '2022-08-01',
    published_at: '2022-08-01',
    approver_user_id: 'hyoeun.kim@flitto.com',
    status: 'P',
    view_count: 300,
    like_count: 100,
    thumbnail_url: '',
    writer_user_photo_url: '',
    tag_list: ['Frontend'],
  },
  {
    post_id: 6,
    writer_user_id: 'hyoeun.kim@flitto.com',
    writer_name: '김효은',
    title: '프론트엔드 스터디 회고',
    content: '안녕하세요. 플리토입니다! 이번 플리토 Server팀',
    created_at: '2022-08-01',
    updated_at: '2022-08-01',
    published_at: '2022-08-01',
    approver_user_id: 'hyoeun.kim@flitto.com',
    status: 'P',
    view_count: 300,
    like_count: 100,
    thumbnail_url: '',
    writer_user_photo_url: '',
    tag_list: ['Frontend', 'Vue.js', 'FrontendFrontendFrontend'],
  },
  {
    post_id: 7,
    writer_user_id: 'hyoeun.kim@flitto.com',
    writer_name: '김효은',
    title: '프론트엔드 스터디 회고',
    content: '안녕하세요. 플리토입니다! 이번 플리토 Server팀',
    created_at: '2022-08-01',
    updated_at: '2022-08-01',
    published_at: '2022-08-01',
    approver_user_id: 'hyoeun.kim@flitto.com',
    status: 'P',
    view_count: 300,
    like_count: 100,
    thumbnail_url: '',
    writer_user_photo_url: '',
    tag_list: ['Frontend', 'React.js'],
  },
  {
    post_id: 8,
    writer_user_id: 'hyoeun.kim@flitto.com',
    writer_name: '김효은',
    title: '프론트엔드 스터디 회고',
    content: '안녕하세요. 플리토입니다! 이번 플리토 Server팀',
    created_at: '2022-08-01',
    updated_at: '2022-08-01',
    published_at: '2022-08-01',
    approver_user_id: 'hyoeun.kim@flitto.com',
    status: 'P',
    view_count: 300,
    like_count: 100,
    thumbnail_url: '',
    writer_user_photo_url: '',
    tag_list: ['React.js'],
  },
  {
    post_id: 9,
    writer_user_id: 'hyoeun.kim@flitto.com',
    writer_name: '김효은',
    title: '프론트엔드 스터디 회고',
    content: '안녕하세요. 플리토입니다! 이번 플리토 Server팀',
    created_at: '2022-08-01',
    updated_at: '2022-08-01',
    published_at: '2022-08-01',
    approver_user_id: 'hyoeun.kim@flitto.com',
    status: 'P',
    view_count: 300,
    like_count: 100,
    thumbnail_url: '',
    writer_user_photo_url: '',
    tag_list: ['Frontend', 'Vue.js'],
  },
  {
    post_id: 10,
    writer_user_id: 'hyoeun.kim@flitto.com',
    writer_name: '김효은',
    title: '프론트엔드 스터디 회고',
    content: '안녕하세요. 플리토입니다! 이번 플리토 Server팀',
    created_at: '2022-08-01',
    updated_at: '2022-08-01',
    published_at: '2022-08-01',
    approver_user_id: 'hyoeun.kim@flitto.com',
    status: 'P',
    view_count: 300,
    like_count: 100,
    thumbnail_url: '',
    writer_user_photo_url: '',
    tag_list: ['Frontend', 'Vue.js'],
  },
  {
    post_id: 11,
    writer_user_id: 'hyoeun.kim@flitto.com',
    writer_name: '김효은',
    title: '프론트엔드 스터디 회고',
    content: '안녕하세요. 플리토입니다! 이번 플리토 Server팀',
    created_at: '2022-08-01',
    updated_at: '2022-08-01',
    published_at: '2022-08-01',
    approver_user_id: 'hyoeun.kim@flitto.com',
    status: 'P',
    view_count: 300,
    like_count: 100,
    thumbnail_url: '',
    writer_user_photo_url: '',
    tag_list: ['Nuxt.js'],
  },
  {
    post_id: 12,
    writer_user_id: 'hyoeun.kim@flitto.com',
    writer_name: '김효은',
    title: '프론트엔드 스터디 회고',
    content: '안녕하세요. 플리토입니다! 이번 플리토 Server팀',
    created_at: '2022-08-01',
    updated_at: '2022-08-01',
    published_at: '2022-08-01',
    approver_user_id: 'hyoeun.kim@flitto.com',
    status: 'P',
    view_count: 300,
    like_count: 100,
    thumbnail_url: '',
    writer_user_photo_url: '',
    tag_list: ['Frontend'],
  },
  {
    post_id: 13,
    writer_user_id: 'hyoeun.kim@flitto.com',
    writer_name: '김효은',
    title: '프론트엔드 스터디 회고',
    content: '안녕하세요. 플리토입니다! 이번 플리토 Server팀',
    created_at: '2022-08-01',
    updated_at: '2022-08-01',
    published_at: '2022-08-01',
    approver_user_id: 'hyoeun.kim@flitto.com',
    status: 'P',
    view_count: 300,
    like_count: 100,
    thumbnail_url: '',
    writer_user_photo_url: '',
    tag_list: ['Vue.js'],
  },
  {
    post_id: 14,
    writer_user_id: 'hyoeun.kim@flitto.com',
    writer_name: '김효은',
    title: '프론트엔드 스터디 회고',
    content:
      '안녕하세요. 플리토입니다! 이번 플리토 Server팀 안녕하세요. 플리토입니다! 이번 플리토 Server팀 안녕하세요. 플리토입니다! 이번 플리토 Server팀 안녕하세요. 플리토입니다! 이번 플리토 Server팀안녕하세요. 플리토입니다! 이번 플리토 Server팀',
    created_at: '2022-08-01',
    updated_at: '2022-08-01',
    published_at: '2022-08-01',
    approver_user_id: 'hyoeun.kim@flitto.com',
    status: 'P',
    view_count: 300,
    like_count: 100,
    thumbnail_url: '',
    writer_user_photo_url: '',
    tag_list: ['Frontend', 'Vue.js'],
  },
]

const userObj = {
  user_id: 3,
  email: 'hyk@flitto.com',
  displayed_name: 'hyoeun.kim',
  photo_url: 'img/vue_logo.png',
  self_description: '안녕하세요',
  user_type: 'A',
  created_at: '2022.06.16',
  updated_at: '2022.06.16',
}

const tagArr = [
  {
    tag_id: 1,
    tag_name: 'Frontend',
    created_at: '2022-08-01',
    tag_count: 26,
  },
  {
    tag_id: 2,
    tag_name: 'Javascript',
    created_at: '2022-08-02',
    tag_count: 16,
  },
  {
    tag_id: 3,
    tag_name: 'Java',
    created_at: '2022-08-03',
    tag_count: 44,
  },
  {
    tag_id: 4,
    tag_name: 'Next.js',
    created_at: '2022-08-04',
    tag_count: 5,
  },
  {
    tag_id: 5,
    tag_name: 'React.js',
    created_at: '2022-08-01',
    tag_count: 8,
  },
]

const notiDataArr = [
  {
    notification_id: 1,
    message: '김도경 님이 flitto_admin 님의 글 발행 요청을 수락하였습니다!',
    redirect_url: '/contentshowpage/12',
    created_at: '2022-08-09 11:27:35',
    read: true,
  },
  {
    notification_id: 2,
    message: '김도경 님이 플리토 님의 글 발행 요청을 수락하였습니다!',
    redirect_url: '/contentshowpage/13',
    created_at: '2022-08-09 10:27:35',
    read: false,
  },
  {
    notification_id: 3,
    message: '김도경 님이 flitto_admin 님의 글 발행 요청을 수락하였습니다!',
    redirect_url: '/contentshowpage/14',
    created_at: '2022-08-08 11:27:35',
    read: false,
  },
  {
    notification_id: 4,
    message:
      'asdfghjklqwertyuiopzxcvbnm 님이 플리토 님의 글 발행 요청을 수락하였습니다!',
    redirect_url: '/contentshowpage/15',
    created_at: '2022-08-08 10:27:35',
    read: false,
  },
  {
    notification_id: 5,
    message: '김도경 님이 플리토 님의 글 발행 요청을 수락하였습니다!',
    redirect_url: '/contentshowpage/15',
    created_at: '2022-08-07 10:27:35',
    read: false,
  },
  {
    notification_id: 6,
    message:
      '<strong>dkkim0122</strong> 님이 <strong>플리토</strong> 님의 글 발행 요청을 수락하였습니다!',
    redirect_url: '/contentshowpage/15',
    created_at: '2022-08-06 10:27:35',
    read: true,
  },
  {
    notification_id: 7,
    message: '김도경 님이 플리토 님의 글 발행 요청을 수락하였습니다!',
    redirect_url: '/contentshowpage/15',
    created_at: '2022-08-05 10:27:35',
    read: false,
  },
  {
    notification_id: 8,
    message: 'brueberry 님이 플리토 님의 글 발행 요청을 수락하였습니다!',
    redirect_url: '/contentshowpage/20',
    created_at: '2022-08-05 13:27:35',
    read: false,
  },
  {
    notification_id: 9,
    message: '김도경 님이 플리토 님의 글 발행 요청을 수락하였습니다!',
    redirect_url: '/contentshowpage/20',
    created_at: '2022-08-05 15:27:35',
    read: false,
  },
]

const authNotiDataArr = [
  // TODO: 임시. 수정 필요
  {
    notification_id: 1,
    message:
      '<strong>김도경</strong> 님이 <strong>관리자 권한</strong>을 <b>신청</b>하셨습니다!',
    redirect_url: '/contentshowpage/12',
    created_at: '2022-08-09 11:27:35',
    read: true,
  },
  {
    notification_id: 2,
    message:
      '<strong>김효은</strong> 님이 <strong>관리자 권한</strong>을 <b>신청</b>하셨습니다!',
    redirect_url: '/contentshowpage/13',
    created_at: '2022-08-09 10:27:35',
    read: false,
  },
  {
    notification_id: 3,
    message:
      '<strong>김소현</strong> 님이 <strong>관리자 권한</strong>을 <b>신청</b>하셨습니다!',
    redirect_url: '/contentshowpage/13',
    created_at: '2022-08-10 09:27:35',
    read: false,
  },
  {
    notification_id: 4,
    message:
      '<strong>이필웅</strong> 님이 <strong>관리자 권한</strong>을 <b>신청</b>하셨습니다!',
    redirect_url: '/contentshowpage/13',
    created_at: '2022-08-10 11:27:35',
    read: false,
  },
  {
    notification_id: 5,
    message:
      '<strong>윤성철</strong> 님이 <strong>관리자 권한</strong>을 <b>신청</b>하셨습니다!',
    redirect_url: '/contentshowpage/13',
    created_at: '2022-08-11 03:27:35',
    read: false,
  },
]

export { postObj, userObj, tagArr, postsArr, notiDataArr, authNotiDataArr }
